shamefullyHoist: true

overrides:
  '@vue/compiler-core': 3.4.21
  '@vue/compiler-dom': 3.4.21
  '@vue/compiler-sfc': 3.4.21
  '@vue/compiler-ssr': 3.4.21
  '@vue/reactivity': 3.4.21
  '@vue/runtime-core': 3.4.21
  '@vue/runtime-dom': 3.4.21
  '@vue/server-renderer': 3.4.21
  '@vue/shared': 3.4.21

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-demi: true
